# name of the action
name: build

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: install go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: build
      run: |
        make build
