# name of the action
name: prerelease

# trigger on push events with `v*` in tag
on:
  push:
    tags:
      - 'v*'

# pipeline to execute
jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        # ensures we fetch tag history for the repository
        fetch-depth: 0

    - name: install go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: setup
      run: |
        # setup git tag in Actions environment
        echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: |
        make build-static-ci

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@4feac4d53e4e55dcc5d3e2ad0ed2e0a76028ff7a # v5
      with:
        name: target/vela-influx
        cache: true
        tag_names: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
