# name of the action
name: validate

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: install go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: validate
      run: |
        # Check that go mod tidy produces a zero diff; clean up any changes afterwards.
        go mod tidy && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go vet ./... produces a zero diff; clean up any changes afterwards.
        go vet ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go fmt ./... produces a zero diff; clean up any changes afterwards.
        go fmt ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go fix ./... produces a zero diff; clean up any changes afterwards.
        go fix ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
